name: modsen.library-api
services:
  - name: modsen-authors
    project: src/Modsen.Authors/Modsen.Authors.csproj
    bindings:
      - port: 3000
  - name: modsen-books
    project: src/Modsen.Books/Modsen.Books.csproj
    bindings:
      - port: 4000
  - name: modsen-library
    project: src/Modsen.Library/Modsen.Library.csproj
    bindings:
      - port: 5000
  - name: rabbit
    image: rabbitmq:3-management
    bindings:
      - protocol: amqp
        port: 5672
  - name: modsen-library-dev
    external: true
    bindings:
      - port: 5432
        connectionString: Host=localhost;Port=${port};Username=modsen_library_dev;Password=modsen_library_dev;