apiVersion: apps/v1
kind: Deployment
metadata:
  name: authors-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorservice
  template:
    metadata:
      labels:
        app: authorservice
    spec:
      containers:
        - name: authorservice
          image: jejikeh/modsen-authors:latest
---
apiVersion: v1
kind: Service
metadata:
  name: authors-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: authorservice
  ports:
    - name: authorservice
      protocol: TCP
      port: 80
      targetPort: 80